### PR TITLE
Also support win32 and small tweaks

### PR DESCRIPTION
**Pull request by littlewhitecloud**
Idk why it fails when I give a hwnd to the `change_header_color`
So I add one more line and some documents

### CODE REVIEW

**Comment by Akascape** [comment]
Bro, why did you add win32? This should only support python ui libraries.

**Comment by littlewhitecloud** [comment]
Maybe I was wrong, I think the name starts with "py" so I think it is a python tool

**Comment by Akascape** [comment]
Lol, this is only for python libraries.

**Comment by littlewhitecloud** [comment]
But it also works fine on win32...

**Comment by littlewhitecloud** [comment]
That's fine, I will close this pr.

**Comment by littlewhitecloud** [comment]
Sorry.

**Comment by Akascape** [comment]
@littlewhitecloud 
> But it also works fine on win32...

Thats fine, people will see this thread if they want to implement it with win32.

**Pull request closed without merging**
